spring.application.name=demo

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=1111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
